version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: proyectoizc
    #restart: always
    depends_on:
      - db-proyectoizc
    ports:
      - 8000:8000
    volumes: 
      - ./proyectoizc/:/app

  db-proyectoizc:
    image: mariadb
    container_name: proyectoizc-db
    #restart: always
    environment:
      MYSQL_DATABASE: proyectoizc
      MYSQL_USER: proyectoizc_user
      MYSQL_PASSWORD: "admin123456"
      MYSQL_ROOT_PASSWORD: admin1234
    volumes:
      - db-proyectoizc:/var/lib/mysql
    ports:
      - 3320:3306

volumes:
  db:    
  db-proyectoizc:    

