# Generated by Django 4.0.2 on 2023-05-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
