# Generated by Django 4.0.2 on 2023-06-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosmuseo',
            name='costoMuseo',
            field=models.CharField(default=1, max_length=100, verbose_name='Costo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosmuseo',
            name='horariosMuseo',
            field=models.CharField(default=1, max_length=100, verbose_name='Horario'),
            preserve_default=False,
        ),
    ]
