# Generated by Django 4.0.2 on 2023-06-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0002_datosmuseo_costomuseo_datosmuseo_horariosmuseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosmuseo',
            name='costoMuseo',
            field=models.CharField(max_length=100, verbose_name='Costo de entrada'),
        ),
        migrations.AlterField(
            model_name='datosmuseo',
            name='datos_generales',
            field=models.CharField(max_length=600, verbose_name='Datos generales'),
        ),
        migrations.AlterField(
            model_name='datosmuseo',
            name='horariosMuseo',
            field=models.CharField(max_length=100, verbose_name='Horarios'),
        ),
    ]
