# Generated by Django 4.0.2 on 2023-06-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0003_alter_datosmuseo_costomuseo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciamuseo',
            unique_together={('museo', 'anio')},
        ),
        migrations.AlterField(
            model_name='asistenciamuseo',
            name='extranjeros_hombres',
            field=models.IntegerField(verbose_name='Extranjeros hombres'),
        ),
        migrations.AlterField(
            model_name='asistenciamuseo',
            name='extranjeros_mujeres',
            field=models.IntegerField(verbose_name='Extranjeros mujeres'),
        ),
        migrations.AlterField(
            model_name='asistenciamuseo',
            name='locales_hombres',
            field=models.IntegerField(verbose_name='Locales hombres'),
        ),
        migrations.AlterField(
            model_name='asistenciamuseo',
            name='locales_mujeres',
            field=models.IntegerField(verbose_name='Locales mujeres'),
        ),
        migrations.AlterField(
            model_name='asistenciamuseo',
            name='nacionales_hombres',
            field=models.IntegerField(verbose_name='Nacionales hombres'),
        ),
        migrations.AlterField(
            model_name='asistenciamuseo',
            name='nacionales_mujeres',
            field=models.IntegerField(verbose_name='Nacionales mujeres'),
        ),
        migrations.RemoveField(
            model_name='asistenciamuseo',
            name='mes',
        ),
    ]
