# Generated by Django 4.0.2 on 2023-05-08 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios_culturales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casacultura',
            name='nombreCasa',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z-ÑñÁáÉéÍíÓóÚú ]+$', 'Sólo se permiten letras, espacios y acentos.')], verbose_name='Nombre'),
        ),
    ]
