# Generated by Django 4.0.2 on 2023-05-08 20:42

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios_culturales', '0002_alter_casacultura_nombrecasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspaciosEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEspacio', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z-ÑñÁáÉéÍíÓóÚú ]+$', 'Sólo se permiten letras, espacios y acentos.')], verbose_name='Nombre')),
                ('datosGenerales', models.TextField(blank=True, verbose_name='Datos Generales')),
                ('aforo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30000)], verbose_name='Aforo')),
                ('municipioEspacio', models.IntegerField(choices=[(0, 'Apozol'), (1, 'Apulco'), (2, 'Atolinga'), (3, 'Benito Juárez'), (4, 'Calera'), (5, 'Cañitas de Felipe Pescador'), (6, 'Concepción del Oro'), (7, 'Cuauhtémoc'), (8, 'Chalchihuites'), (9, 'Fresnillo'), (10, 'Trinidad García de la Cadena'), (11, 'Genaro Codina'), (12, 'General Enrique Estrada'), (13, 'General Francisco R. Murguía'), (14, 'El Plateado de Joaquín Amaro'), (15, 'General Pánfilo Natera'), (16, 'Guadalupe'), (17, 'Huanusco'), (18, 'Jalpa'), (19, 'Jerez'), (20, 'Jiménez del Teul'), (21, 'Juan Aldama'), (22, 'Juchipila'), (23, 'Loreto'), (24, 'Luis Moya'), (25, 'Mazapil'), (26, 'Melchor Ocampo'), (27, 'Mezquital del Oro'), (28, 'Miguel Auza'), (29, 'Momax'), (30, 'Monte Escobedo'), (31, 'Morelos'), (32, 'Moyahua de Estrada'), (33, 'Nochistlán de Mejía'), (34, 'Noria de Ángeles'), (35, 'Ojocaliente'), (36, 'Pánuco'), (37, 'Pinos'), (38, 'Río Grande'), (39, 'Sain Alto'), (40, 'El Salvador'), (41, 'Sombrerete'), (42, 'Susticacán'), (43, 'Tabasco'), (44, 'Tepechitlán'), (45, 'Tepetongo'), (46, 'Teúl de González Ortega'), (47, 'Tlaltenango de Sánchez Román'), (48, 'Valparaíso'), (49, 'Vetagrande'), (50, 'Villa de Cos'), (51, 'Villa García'), (52, 'Villa González Ortega'), (53, 'Villa Hidalgo'), (54, 'Villanueva'), (55, 'Zacatecas'), (56, 'Trancoso'), (57, 'Santa María de la Paz')], verbose_name='Municipio')),
                ('tipoEspacio', models.IntegerField(choices=[(0, 'Auditorio'), (1, 'Teatro')], verbose_name='Tipo de Espacio')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
            ],
        ),
        migrations.RenameField(
            model_name='casacultura',
            old_name='location',
            new_name='ubicacion',
        ),
    ]
