# Generated by Django 4.0.2 on 2023-03-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.IntegerField(choices=[(0, 'Femenino'), (1, 'Masculino'), (2, 'Otro')], verbose_name='Género')),
                ('contacto', models.CharField(max_length=100, verbose_name='Número de contacto')),
                ('municipioCreador', models.IntegerField(choices=[(0, 'Apozol'), (1, 'Apulco'), (2, 'Atolinga'), (3, 'Benito Juárez'), (4, 'Calera'), (5, 'Cañitas de Felipe Pescador'), (6, 'Concepción del Oro'), (7, 'Cuauhtémoc'), (8, 'Chalchihuites'), (9, 'Fresnillo'), (10, 'Trinidad García de la Cadena'), (11, 'Genaro Codina'), (12, 'General Enrique Estrada'), (13, 'General Francisco R. Murguía'), (14, 'El Plateado de Joaquín Amaro'), (15, 'General Pánfilo Natera'), (16, 'Guadalupe'), (17, 'Huanusco'), (18, 'Jalpa'), (19, 'Jerez'), (20, 'Jiménez del Teul'), (21, 'Juan Aldama'), (22, 'Juchipila'), (23, 'Loreto'), (24, 'Luis Moya'), (25, 'Mazapil'), (26, 'Melchor Ocampo'), (27, 'Mezquital del Oro'), (28, 'Miguel Auza'), (29, 'Momax'), (30, 'Monte Escobedo'), (31, 'Morelos'), (32, 'Moyahua de Estrada'), (33, 'Nochistlán de Mejía'), (34, 'Noria de Ángeles'), (35, 'Ojocaliente'), (36, 'Pánuco'), (37, 'Pinos'), (38, 'Río Grande'), (39, 'Sain Alto'), (40, 'El Salvador'), (41, 'Sombrerete'), (42, 'Susticacán'), (43, 'Tabasco'), (44, 'Tepechitlán'), (45, 'Tepetongo'), (46, 'Teúl de González Ortega'), (47, 'Tlaltenango de Sánchez Román'), (48, 'Valparaíso'), (49, 'Vetagrande'), (50, 'Villa de Cos'), (51, 'Villa García'), (52, 'Villa González Ortega'), (53, 'Villa Hidalgo'), (54, 'Villanueva'), (55, 'Zacatecas'), (56, 'Trancoso'), (57, 'Santa María de la Paz')], verbose_name='Municipio')),
                ('localidadCreador', models.CharField(max_length=100, verbose_name='Localidad')),
                ('escolaridadCreador', models.IntegerField(choices=[(0, 'Primaria'), (1, 'Secundiaria'), (2, 'Media superior'), (3, 'Superior'), (4, 'Posgrado'), (5, 'Maestría'), (6, 'Doctorado')], verbose_name='Escolaridad')),
                ('disciplinaCreador', models.IntegerField(choices=[(0, 'Cantante'), (1, 'Pintor'), (2, 'Danzante'), (3, 'Artista plástico'), (4, 'Escultor'), (5, 'Músico'), (6, 'Escritor'), (7, 'Actor'), (8, 'Cantautor')], verbose_name='Disciplina')),
                ('especialidadCreador', models.CharField(blank=True, max_length=100, verbose_name='Especialidad')),
                ('otraDisciplinaCreador', models.CharField(blank=True, max_length=100, verbose_name='Otras disciplinas')),
                ('opcionCreador', models.IntegerField(choices=[(0, 'Individual'), (1, 'Grupal')], verbose_name='Como se desempeña')),
                ('gradoConocimientoCreador', models.IntegerField(choices=[(0, 'Licenciatura'), (1, 'Empírico'), (2, 'Talleres')], verbose_name='Conocimiento artistico')),
                ('lugarFormacionCreador', models.CharField(blank=True, max_length=100, verbose_name='Lugar de formación')),
                ('vigenciaCreador', models.IntegerField(choices=[(0, 'Vigente'), (1, 'No vigente')], verbose_name='Vigencia')),
                ('imagenCreador', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
