# Generated by Django 4.0.2 on 2023-05-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creadores',
            name='vigenciaCreador',
            field=models.IntegerField(choices=[(0, 'Activo'), (1, 'No activo')], verbose_name='Vigencia'),
        ),
    ]
