"""
Django settings for ProyectoIZC project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wb064cfij!1@p_vxqr270z8w22a3dzyr6hrbxr3-!_wq4+0sgq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jquery',
    'usuarios',
    'home',
    'django.contrib.gis',
    'espacios_culturales',
    'platillos',
    'creadores',
    'eventos',
    'institutos_culturales',
    'museos',
    'mapwidgets',
    
    
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ProyectoIZC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProyectoIZC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.mysql', #Configurar el motor para usar bdd espacial.
        'NAME': 'proyectoizc',
        'USER': 'root',
        'PASSWORD': 'admin1234',
        'HOST': 'db-proyectoizc',
        'PORT': 3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/


LANGUAGE_CODE = 'es-mx'
USE_TZ = True
TIME_ZONE = 'America/Mexico_City'  # Ajusta la zona horaria según tu ubicación

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

MEDIA_ROOT = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Location of static files
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL después de loguearse.
LOGIN_URL = '/'

GOOGLE_MAPS_API_KEY = ''

MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 10),
        ("mapCenterLocation", [22.767261670806203, -102.58038960135332]),
         ("GooglePlaceAutocompleteOptions", {'componentRestrictions': {'country': 'mx'}}),
        ("markerFitZoom", 12),
        ("streetViewControl", True),
    ),
    "GOOGLE_MAP_API_KEY": GOOGLE_MAPS_API_KEY
}


#email-backend
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


MUNICIPIOS = [
    (0,'Apozol'),
    (1,'Apulco'),
    (2,'Atolinga'),
    (3,'Benito Juárez'),
    (4,'Calera'),
    (5,'Cañitas de Felipe Pescador'),
    (6,'Concepción del Oro'),
    (7,'Cuauhtémoc'),
    (8,'Chalchihuites'),
    (9,'Fresnillo'),
    (10,'Trinidad García de la Cadena'),
    (11,'Genaro Codina'),
    (12,'General Enrique Estrada'),
    (13,'General Francisco R. Murguía'),
    (14,'El Plateado de Joaquín Amaro'),
    (15,'General Pánfilo Natera'),
    (16,'Guadalupe'),
    (17,'Huanusco'),
    (18,'Jalpa'),
    (19,'Jerez'),
    (20,'Jiménez del Teul'),
    (21,'Juan Aldama'),
    (22,'Juchipila'),
    (23,'Loreto'),
    (24,'Luis Moya'),
    (25,'Mazapil'),
    (26,'Melchor Ocampo'),
    (27,'Mezquital del Oro'),
    (28,'Miguel Auza'),
    (29,'Momax'),
    (30,'Monte Escobedo'),
    (31,'Morelos'),
    (32,'Moyahua de Estrada'),
    (33,'Nochistlán de Mejía'),
    (34,'Noria de Ángeles'),
    (35,'Ojocaliente'),
    (36,'Pánuco'),
    (37,'Pinos'),
    (38,'Río Grande'),
    (39,'Sain Alto'),
    (40,'El Salvador'),
    (41,'Sombrerete'),
    (42,'Susticacán'),
    (43,'Tabasco'),
    (44,'Tepechitlán'),
    (45,'Tepetongo'),
    (46,'Teúl de González Ortega'),
    (47,'Tlaltenango de Sánchez Román'),
    (48,'Valparaíso'),
    (49,'Vetagrande'),
    (50,'Villa de Cos'),
    (51,'Villa García'),
    (52,'Villa González Ortega'),
    (53,'Villa Hidalgo'),
    (54,'Villanueva'),
    (55,'Zacatecas'),
    (56,'Trancoso'),
    (57,'Santa María de la Paz'),
]

