# Generated by Django 4.0.2 on 2023-05-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEvento', models.CharField(max_length=100, unique=True, verbose_name='Evento')),
                ('informesEvento', models.TextField(null=True, verbose_name='Informes')),
                ('municipioEvento', models.IntegerField(choices=[(0, 'Apozol'), (1, 'Apulco'), (2, 'Atolinga'), (3, 'Benito Juárez'), (4, 'Calera'), (5, 'Cañitas de Felipe Pescador'), (6, 'Concepción del Oro'), (7, 'Cuauhtémoc'), (8, 'Chalchihuites'), (9, 'Fresnillo'), (10, 'Trinidad García de la Cadena'), (11, 'Genaro Codina'), (12, 'General Enrique Estrada'), (13, 'General Francisco R. Murguía'), (14, 'El Plateado de Joaquín Amaro'), (15, 'General Pánfilo Natera'), (16, 'Guadalupe'), (17, 'Huanusco'), (18, 'Jalpa'), (19, 'Jerez'), (20, 'Jiménez del Teul'), (21, 'Juan Aldama'), (22, 'Juchipila'), (23, 'Loreto'), (24, 'Luis Moya'), (25, 'Mazapil'), (26, 'Melchor Ocampo'), (27, 'Mezquital del Oro'), (28, 'Miguel Auza'), (29, 'Momax'), (30, 'Monte Escobedo'), (31, 'Morelos'), (32, 'Moyahua de Estrada'), (33, 'Nochistlán de Mejía'), (34, 'Noria de Ángeles'), (35, 'Ojocaliente'), (36, 'Pánuco'), (37, 'Pinos'), (38, 'Río Grande'), (39, 'Sain Alto'), (40, 'El Salvador'), (41, 'Sombrerete'), (42, 'Susticacán'), (43, 'Tabasco'), (44, 'Tepechitlán'), (45, 'Tepetongo'), (46, 'Teúl de González Ortega'), (47, 'Tlaltenango de Sánchez Román'), (48, 'Valparaíso'), (49, 'Vetagrande'), (50, 'Villa de Cos'), (51, 'Villa García'), (52, 'Villa González Ortega'), (53, 'Villa Hidalgo'), (54, 'Villanueva'), (55, 'Zacatecas'), (56, 'Trancoso'), (57, 'Santa María de la Paz')], verbose_name='Municipio')),
                ('tipoEvento', models.IntegerField(choices=[(0, 'Ferias del libro'), (1, 'Festivales'), (2, 'Festividades'), (3, 'Otro')], verbose_name='Tipo de evento')),
                ('subTipoEvento', models.IntegerField(choices=[(0, 'Multidiciplinaria'), (1, 'Danza'), (2, 'Teatro'), (3, 'Música'), (4, 'Literatura'), (5, 'Otro')], verbose_name='Categoría de evento')),
                ('descripcionEvento', models.TextField(null=True, verbose_name='Descripción')),
                ('sedeEvento', models.CharField(max_length=100, null=True, verbose_name='Sede')),
                ('fechaDeEvento', models.TextField(null=True, verbose_name='Fecha del evento')),
                ('institucionOrganizadora', models.CharField(max_length=100, null=True, verbose_name='Institucion organizadora')),
                ('institucionCoadyuvante', models.CharField(max_length=100, null=True, verbose_name='Instituciones coadyuvantes')),
                ('imagenEvento', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['nombreEvento'],
            },
        ),
    ]
