# Generated by Django 4.0.2 on 2023-05-21 05:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutoCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreInstituto', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('datosGeneralesIns', models.TextField(blank=True, verbose_name='Datos Generales')),
                ('municipioInstituto', models.IntegerField(choices=[(0, 'Apozol'), (1, 'Apulco'), (2, 'Atolinga'), (3, 'Benito Juárez'), (4, 'Calera'), (5, 'Cañitas de Felipe Pescador'), (6, 'Concepción del Oro'), (7, 'Cuauhtémoc'), (8, 'Chalchihuites'), (9, 'Fresnillo'), (10, 'Trinidad García de la Cadena'), (11, 'Genaro Codina'), (12, 'General Enrique Estrada'), (13, 'General Francisco R. Murguía'), (14, 'El Plateado de Joaquín Amaro'), (15, 'General Pánfilo Natera'), (16, 'Guadalupe'), (17, 'Huanusco'), (18, 'Jalpa'), (19, 'Jerez'), (20, 'Jiménez del Teul'), (21, 'Juan Aldama'), (22, 'Juchipila'), (23, 'Loreto'), (24, 'Luis Moya'), (25, 'Mazapil'), (26, 'Melchor Ocampo'), (27, 'Mezquital del Oro'), (28, 'Miguel Auza'), (29, 'Momax'), (30, 'Monte Escobedo'), (31, 'Morelos'), (32, 'Moyahua de Estrada'), (33, 'Nochistlán de Mejía'), (34, 'Noria de Ángeles'), (35, 'Ojocaliente'), (36, 'Pánuco'), (37, 'Pinos'), (38, 'Río Grande'), (39, 'Sain Alto'), (40, 'El Salvador'), (41, 'Sombrerete'), (42, 'Susticacán'), (43, 'Tabasco'), (44, 'Tepechitlán'), (45, 'Tepetongo'), (46, 'Teúl de González Ortega'), (47, 'Tlaltenango de Sánchez Román'), (48, 'Valparaíso'), (49, 'Vetagrande'), (50, 'Villa de Cos'), (51, 'Villa García'), (52, 'Villa González Ortega'), (53, 'Villa Hidalgo'), (54, 'Villanueva'), (55, 'Zacatecas'), (56, 'Trancoso'), (57, 'Santa María de la Paz')], verbose_name='Municipio')),
                ('directorInstituto', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Director')),
                ('personalTotal', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Personal')),
                ('ubicacionInstituto', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación')),
                ('imagenInstituto', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidadTaller', models.IntegerField(choices=[(0, 'Regular'), (1, 'Libre')], verbose_name='Modalidad')),
                ('conduccionTaller', models.IntegerField(choices=[(0, 'Presencial'), (1, 'A Distancia')], verbose_name='Conduccion')),
                ('nivelTaller', models.IntegerField(choices=[(0, 'Profesional'), (1, 'Iniciación'), (2, 'Producción'), (3, 'Técnico')], verbose_name='Nivel')),
                ('nombreTaller', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('generoTaller', models.IntegerField(choices=[(0, 'Música'), (1, 'Artes visuales'), (2, 'Teatro'), (3, 'Danza'), (4, 'Literatura'), (5, 'Cine')], verbose_name='Género')),
                ('disciplinaTaller', models.CharField(max_length=100, null=True, verbose_name='Disciplina')),
                ('coberturaTaller', models.CharField(max_length=100, null=True, verbose_name='Cobertura')),
                ('foroEspacioTaller', models.CharField(max_length=100, null=True, verbose_name='Foro o Espacio')),
                ('municipioTaller', models.IntegerField(choices=[(0, 'Apozol'), (1, 'Apulco'), (2, 'Atolinga'), (3, 'Benito Juárez'), (4, 'Calera'), (5, 'Cañitas de Felipe Pescador'), (6, 'Concepción del Oro'), (7, 'Cuauhtémoc'), (8, 'Chalchihuites'), (9, 'Fresnillo'), (10, 'Trinidad García de la Cadena'), (11, 'Genaro Codina'), (12, 'General Enrique Estrada'), (13, 'General Francisco R. Murguía'), (14, 'El Plateado de Joaquín Amaro'), (15, 'General Pánfilo Natera'), (16, 'Guadalupe'), (17, 'Huanusco'), (18, 'Jalpa'), (19, 'Jerez'), (20, 'Jiménez del Teul'), (21, 'Juan Aldama'), (22, 'Juchipila'), (23, 'Loreto'), (24, 'Luis Moya'), (25, 'Mazapil'), (26, 'Melchor Ocampo'), (27, 'Mezquital del Oro'), (28, 'Miguel Auza'), (29, 'Momax'), (30, 'Monte Escobedo'), (31, 'Morelos'), (32, 'Moyahua de Estrada'), (33, 'Nochistlán de Mejía'), (34, 'Noria de Ángeles'), (35, 'Ojocaliente'), (36, 'Pánuco'), (37, 'Pinos'), (38, 'Río Grande'), (39, 'Sain Alto'), (40, 'El Salvador'), (41, 'Sombrerete'), (42, 'Susticacán'), (43, 'Tabasco'), (44, 'Tepechitlán'), (45, 'Tepetongo'), (46, 'Teúl de González Ortega'), (47, 'Tlaltenango de Sánchez Román'), (48, 'Valparaíso'), (49, 'Vetagrande'), (50, 'Villa de Cos'), (51, 'Villa García'), (52, 'Villa González Ortega'), (53, 'Villa Hidalgo'), (54, 'Villanueva'), (55, 'Zacatecas'), (56, 'Trancoso'), (57, 'Santa María de la Paz')], verbose_name='Municipio')),
                ('localidadTaller', models.CharField(max_length=100, null=True, verbose_name='Localidad')),
                ('frecuenciaTaller', models.IntegerField(choices=[(0, 'Unica ocasión'), (1, 'Semanal'), (2, 'Mensual'), (3, 'Trimestral'), (4, 'Otro')], verbose_name='Frecuencia')),
                ('fechaRealizacionTaller', models.CharField(max_length=100, null=True, verbose_name='Fecha')),
                ('nombreInstructorTaller', models.CharField(max_length=100, null=True, verbose_name='Nombre del Instructor')),
                ('procedenciaInstructorTaller', models.CharField(max_length=100, null=True, verbose_name='Procedencia del Instructor')),
                ('ninosTaller', models.CharField(max_length=100, null=True, verbose_name='Alumnos niños')),
                ('ninasTaller', models.CharField(max_length=100, null=True, verbose_name='Alumnos niñas')),
                ('jovenesHombresTaller', models.CharField(max_length=100, null=True, verbose_name='Jovenes hombres')),
                ('jovenesMujeresTaller', models.CharField(max_length=100, null=True, verbose_name='Jovenes mujeres')),
                ('adultosHombresTaller', models.CharField(max_length=100, null=True, verbose_name='Adultos hombres')),
                ('adultosMujeresTaller', models.CharField(max_length=100, null=True, verbose_name='Adultos mujeres')),
                ('fuenteInformacionTaller', models.CharField(max_length=100, null=True, verbose_name='Fuente de información')),
                ('observacionesTaller', models.TextField(null=True, verbose_name='Observaciones')),
                ('evidenciasTaller', models.CharField(max_length=300, null=True, verbose_name='Evidencias del Taller')),
                ('institucionResponsableTaller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutos_culturales.institutocultural', verbose_name='Institucion responsable')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionEditorialInstitutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProduccionInst', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('generoProduccionInst', models.IntegerField(choices=[(0, 'Musica'), (1, 'Artes visuales'), (3, 'Teatro'), (4, 'Danza'), (5, 'Literatura'), (6, 'Cine'), (6, 'Historia'), (7, 'Gastronomía'), (8, 'Monografía'), (9, 'Otro')], verbose_name='Genero')),
                ('disciplinaProduccionInst', models.CharField(max_length=100, null=True, verbose_name='Disciplina')),
                ('cantidadTirajeInst', models.CharField(max_length=100, null=True, verbose_name='Cobertura')),
                ('fechaPublicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('nombreAutorInst', models.CharField(max_length=100, null=True, verbose_name='Nombre del Autor')),
                ('procedenciaAutorInst', models.CharField(max_length=100, null=True, verbose_name='Procedencia del Autor')),
                ('numeroAutoresHombresInst', models.CharField(max_length=100, null=True, verbose_name='No. Autores Hombres')),
                ('numeroAutoresMujeresInst', models.CharField(max_length=100, null=True, verbose_name='No. Autores Mujeres')),
                ('fuenteInformacionProduccionInst', models.CharField(max_length=100, null=True, verbose_name='Fuente de información')),
                ('observacionesProduccionInst', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('evidenciasProduccion', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('institucionResponsableDeProduccionInst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutos_culturales.institutocultural', verbose_name='Institucion responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Exposiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoExposicion', models.IntegerField(choices=[(0, 'Permanente'), (1, 'Temporal'), (2, 'Itirenante'), (3, 'Colectiva')], verbose_name='Tipo')),
                ('nombreExposicion', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('generoExposicion', models.IntegerField(choices=[(0, 'Artes visuales'), (1, 'Historia'), (2, 'Antroplogía'), (3, 'Artes plásticas'), (4, 'Multidisciplinario')], verbose_name='Género')),
                ('disciplinaTecnicaExposicion', models.CharField(max_length=100, null=True, verbose_name='Disciplina')),
                ('nombreEspecialistaExposicion', models.CharField(max_length=100, null=True, verbose_name='Nombre del especialista')),
                ('procedenciaEspecialistaExposicion', models.CharField(max_length=100, null=True, verbose_name='Procedencia del especialista')),
                ('numeroExpositores', models.CharField(max_length=100, null=True, verbose_name='Numero de Expositores')),
                ('foroEspacioExposicion', models.CharField(max_length=100, null=True, verbose_name='Foro o Espacio')),
                ('periodoExposicion', models.CharField(max_length=100, null=True, verbose_name='Periodo de Exposicion')),
                ('fechaInauguracionExposicion', models.CharField(max_length=100, null=True, verbose_name='Fecha de Inauguración')),
                ('municipioExposicion', models.IntegerField(choices=[(0, 'Apozol'), (1, 'Apulco'), (2, 'Atolinga'), (3, 'Benito Juárez'), (4, 'Calera'), (5, 'Cañitas de Felipe Pescador'), (6, 'Concepción del Oro'), (7, 'Cuauhtémoc'), (8, 'Chalchihuites'), (9, 'Fresnillo'), (10, 'Trinidad García de la Cadena'), (11, 'Genaro Codina'), (12, 'General Enrique Estrada'), (13, 'General Francisco R. Murguía'), (14, 'El Plateado de Joaquín Amaro'), (15, 'General Pánfilo Natera'), (16, 'Guadalupe'), (17, 'Huanusco'), (18, 'Jalpa'), (19, 'Jerez'), (20, 'Jiménez del Teul'), (21, 'Juan Aldama'), (22, 'Juchipila'), (23, 'Loreto'), (24, 'Luis Moya'), (25, 'Mazapil'), (26, 'Melchor Ocampo'), (27, 'Mezquital del Oro'), (28, 'Miguel Auza'), (29, 'Momax'), (30, 'Monte Escobedo'), (31, 'Morelos'), (32, 'Moyahua de Estrada'), (33, 'Nochistlán de Mejía'), (34, 'Noria de Ángeles'), (35, 'Ojocaliente'), (36, 'Pánuco'), (37, 'Pinos'), (38, 'Río Grande'), (39, 'Sain Alto'), (40, 'El Salvador'), (41, 'Sombrerete'), (42, 'Susticacán'), (43, 'Tabasco'), (44, 'Tepechitlán'), (45, 'Tepetongo'), (46, 'Teúl de González Ortega'), (47, 'Tlaltenango de Sánchez Román'), (48, 'Valparaíso'), (49, 'Vetagrande'), (50, 'Villa de Cos'), (51, 'Villa García'), (52, 'Villa González Ortega'), (53, 'Villa Hidalgo'), (54, 'Villanueva'), (55, 'Zacatecas'), (56, 'Trancoso'), (57, 'Santa María de la Paz')], verbose_name='Municipio:')),
                ('localidadExposicion', models.CharField(max_length=100, null=True, verbose_name='Localidad')),
                ('coberturaExposicion', models.CharField(max_length=100, null=True, verbose_name='Cobertura')),
                ('ninosExposicion', models.CharField(max_length=100, null=True, verbose_name='Alumnos niños')),
                ('ninasExposicion', models.CharField(max_length=100, null=True, verbose_name='Alumnos niñas')),
                ('jovenesHombresExposicion', models.CharField(max_length=100, null=True, verbose_name='Jovenes hombres')),
                ('jovenesMujeresExposicion', models.CharField(max_length=100, null=True, verbose_name='Jovenes mujeres')),
                ('adultosHombresExposicion', models.CharField(max_length=100, null=True, verbose_name='Adultos hombres')),
                ('adultosMujeresExposicion', models.CharField(max_length=100, null=True, verbose_name='Adultos mujeres')),
                ('fuenteInformacionExposicion', models.CharField(max_length=100, null=True, verbose_name='Fuente de información')),
                ('observacionesExposicion', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('evidenciasExposicion', models.CharField(max_length=300, null=True, verbose_name='Evidencias')),
                ('institucionResponsableDeExposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutos_culturales.institutocultural', verbose_name='Institucion responsable')),
            ],
        ),
        migrations.CreateModel(
            name='EventosInstitutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEventoInst', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('generoEventoInst', models.IntegerField(choices=[(0, 'Música'), (1, 'Artes visuales'), (2, 'Artes escénicas'), (3, 'Danza'), (4, 'Literatira'), (5, 'Filosofía'), (6, 'Historia'), (7, 'Antroplogía'), (8, 'Artes plásticas'), (9, 'Oratoria'), (10, 'Multidisciplinario')], verbose_name='Género')),
                ('disciplinaEventoInst', models.CharField(max_length=100, null=True, verbose_name='Disciplina')),
                ('foroEspacioEventoInst', models.CharField(max_length=100, null=True, verbose_name='Foro o Espacio')),
                ('municipioEventoInst', models.IntegerField(choices=[(0, 'Apozol'), (1, 'Apulco'), (2, 'Atolinga'), (3, 'Benito Juárez'), (4, 'Calera'), (5, 'Cañitas de Felipe Pescador'), (6, 'Concepción del Oro'), (7, 'Cuauhtémoc'), (8, 'Chalchihuites'), (9, 'Fresnillo'), (10, 'Trinidad García de la Cadena'), (11, 'Genaro Codina'), (12, 'General Enrique Estrada'), (13, 'General Francisco R. Murguía'), (14, 'El Plateado de Joaquín Amaro'), (15, 'General Pánfilo Natera'), (16, 'Guadalupe'), (17, 'Huanusco'), (18, 'Jalpa'), (19, 'Jerez'), (20, 'Jiménez del Teul'), (21, 'Juan Aldama'), (22, 'Juchipila'), (23, 'Loreto'), (24, 'Luis Moya'), (25, 'Mazapil'), (26, 'Melchor Ocampo'), (27, 'Mezquital del Oro'), (28, 'Miguel Auza'), (29, 'Momax'), (30, 'Monte Escobedo'), (31, 'Morelos'), (32, 'Moyahua de Estrada'), (33, 'Nochistlán de Mejía'), (34, 'Noria de Ángeles'), (35, 'Ojocaliente'), (36, 'Pánuco'), (37, 'Pinos'), (38, 'Río Grande'), (39, 'Sain Alto'), (40, 'El Salvador'), (41, 'Sombrerete'), (42, 'Susticacán'), (43, 'Tabasco'), (44, 'Tepechitlán'), (45, 'Tepetongo'), (46, 'Teúl de González Ortega'), (47, 'Tlaltenango de Sánchez Román'), (48, 'Valparaíso'), (49, 'Vetagrande'), (50, 'Villa de Cos'), (51, 'Villa García'), (52, 'Villa González Ortega'), (53, 'Villa Hidalgo'), (54, 'Villanueva'), (55, 'Zacatecas'), (56, 'Trancoso'), (57, 'Santa María de la Paz')], verbose_name='Municipio')),
                ('localidadEventoInst', models.CharField(max_length=100, null=True, verbose_name='Localidad')),
                ('fechaRealizacionEventoInst', models.CharField(max_length=100, null=True, verbose_name='Fecha')),
                ('nombreCreadorEventoInst', models.CharField(max_length=100, null=True, verbose_name='Artista y/o grupo')),
                ('procedenciaCreadorEventoInst', models.CharField(max_length=100, null=True, verbose_name='Procedencia')),
                ('numeroCreadoresHombresEventoInst', models.CharField(max_length=100, null=True, verbose_name='No.Hombres')),
                ('numeroCreadoresMujeresEventoInst', models.CharField(max_length=100, null=True, verbose_name='No. Mujeres')),
                ('ninosEventoInst', models.CharField(max_length=100, null=True, verbose_name='Niños')),
                ('ninasEventoInst', models.CharField(max_length=100, null=True, verbose_name='Niñas')),
                ('jovenesHombresEventoInst', models.CharField(max_length=100, null=True, verbose_name='Jovenes hombres')),
                ('jovenesMujeresEventoInst', models.CharField(max_length=100, null=True, verbose_name='Jovenes mujeres')),
                ('adultosHombresEventoInst', models.CharField(max_length=100, null=True, verbose_name='Adultos hombres')),
                ('adultosMujeresEventoInst', models.CharField(max_length=100, null=True, verbose_name='Adultos mujeres')),
                ('fuenteInformacionEventoInst', models.CharField(max_length=100, null=True, verbose_name='Fuente de información')),
                ('observacionesEventoInst', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('evidenciasEventoInst', models.CharField(max_length=300, null=True, verbose_name='Evidencias')),
                ('institucionResponsableDeEventoInst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutos_culturales.institutocultural', verbose_name='Institucion responsable')),
            ],
        ),
    ]
