# Generated by Django 4.0.2 on 2023-05-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos_culturales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccioneditorialinstitutos',
            name='fechaPublicacion',
        ),
        migrations.AddField(
            model_name='produccioneditorialinstitutos',
            name='fechaDePublicacion',
            field=models.CharField(max_length=100, null=True, verbose_name='Fecha'),
        ),
    ]
